const translations = {
    'af-ZA': {
        loading: "Besig om lirieke te laai",
        notFound: "Kon nie die lirieke vind nie.",
        writtenBy: "Geskryf deur: ",
        source: "Lirieke Verskaf Deur: ",
        notFoundError: "Dit lyk of ons nie die lirieke kan vertoon nie.",
        showTranslation: "Wys Vertaling",
        hideTranslation: "Versteek Vertaling",
        showPronunciation: "Wys Uitspraak",
        hidePronunciation: "Versteek Uitspraak",
        showOriginal: "Wys Oorspronklike",
        hideOriginal: "Versteek Oorspronklike",
        refreshLyrics: "Verfris lirieke",
        showTranslationOptions: "Wys vertaalopsies"
    },
    'az-AZ': {
        loading: "Mahnı sözləri yüklənir",
        notFound: "Mahnı sözləri tapılmadı.",
        writtenBy: "Müəllif: ",
        source: "Mahnı Sözləri Təmin Edildi: ",
        notFoundError: "Görünür, mahnı sözlərini göstərə bilmirik.",
        showTranslation: "Tərcüməni Göstər",
        hideTranslation: "Tərcüməni Gizlət",
        showPronunciation: "Tələffüzü Göstər",
        hidePronunciation: "Tələffüzü Gizlət",
        showOriginal: "Orijinalı Göstər",
        hideOriginal: "Orijinalı Gizlət",
        refreshLyrics: "Mahnı sözlərini yenilə",
        showTranslationOptions: "Tərcümə seçimlərini göstər"
    },
    'id-ID': {
        loading: "Memuat lirik",
        notFound: "Tidak dapat menemukan lirik.",
        writtenBy: "Ditulis oleh: ",
        source: "Lirik Disediakan Oleh: ",
        notFoundError: "Sepertinya kami tidak dapat menampilkan lirik.",
        showTranslation: "Tampilkan Terjemahan",
        hideTranslation: "Sembunyikan Terjemahan",
        showPronunciation: "Tampilkan Pelafalan",
        hidePronunciation: "Sembunyikan Pelafalan",
        showOriginal: "Tampilkan Asli",
        hideOriginal: "Sembunyikan Asli",
        refreshLyrics: "Muat ulang lirik",
        showTranslationOptions: "Tampilkan opsi terjemahan"
    },
    'ms-MY': {
        loading: "Memuatkan lirik",
        notFound: "Tidak dapat mencari lirik.",
        writtenBy: "Ditulis oleh: ",
        source: "Lirik Disediakan Oleh: ",
        notFoundError: "Nampaknya kami tidak dapat memaparkan lirik.",
        showTranslation: "Tunjukkan Terjemahan",
        hideTranslation: "Sembunyikan Terjemahan",
        showPronunciation: "Tunjukkan Sebutan",
        hidePronunciation: "Sembunyikan Sebutan",
        showOriginal: "Tunjukkan Asal",
        hideOriginal: "Sembunyikan Asal",
        refreshLyrics: "Muat semula lirik",
        showTranslationOptions: "Tunjukkan pilihan terjemahan"
    },
    'bs-BA': {
        loading: "Učitavanje teksta",
        notFound: "Nije moguće pronaći tekst.",
        writtenBy: "Napisao/la: ",
        source: "Tekst obezbijedio/la: ",
        notFoundError: "Čini se da ne možemo prikazati tekst.",
        showTranslation: "Prikaži prijevod",
        hideTranslation: "Sakrij prijevod",
        showPronunciation: "Prikaži izgovor",
        hidePronunciation: "Sakrij izgovor",
        showOriginal: "Prikaži Original",
        hideOriginal: "Sakrij Original",
        refreshLyrics: "Osvježi tekst",
        showTranslationOptions: "Prikaži opcije prijevoda"
    },
    'ca-ES': {
        loading: "Carregant lletres",
        notFound: "No s'han pogut trobar les lletres.",
        writtenBy: "Escrit per: ",
        source: "Lletres proporcionades per: ",
        notFoundError: "Sembla que no podem mostrar les lletres.",
        showTranslation: "Mostra la traducció",
        hideTranslation: "Amaga la traducció",
        showPronunciation: "Mostra la pronunciació",
        hidePronunciation: "Amaga la pronunciació",
        showOriginal: "Mostra Original",
        hideOriginal: "Amaga Original",
        refreshLyrics: "Actualitza lletres",
        showTranslationOptions: "Mostra opcions de traducció"
    },
    'cs-CZ': {
        loading: "Načítání textů",
        notFound: "Nepodařilo se najít texty.",
        writtenBy: "Napsal(a): ",
        source: "Texty poskytl(a): ",
        notFoundError: "Zdá se, že nemůžeme zobrazit texty.",
        showTranslation: "Zobrazit překlad",
        hideTranslation: "Skrýt překlad",
        showPronunciation: "Zobrazit výslovnost",
        hidePronunciation: "Skrýt výslovnost",
        showOriginal: "Zobrazit Originál",
        hideOriginal: "Skrýt Originál",
        refreshLyrics: "Obnovit texty",
        showTranslationOptions: "Zobrazit možnosti překladu"
    },
    'da-DK': {
        loading: "Indlæser sangtekster",
        notFound: "Kunne ikke finde sangteksterne.",
        writtenBy: "Skrevet af: ",
        source: "Sangtekster leveret af: ",
        notFoundError: "Det ser ud til, at vi ikke kan vise sangteksterne.",
        showTranslation: "Vis oversættelse",
        hideTranslation: "Skjul oversættelse",
        showPronunciation: "Vis udtale",
        hidePronunciation: "Skjul udtale",
        showOriginal: "Vis Original",
        hideOriginal: "Skjul Original",
        refreshLyrics: "Genindlæs sangtekster",
        showTranslationOptions: "Vis oversættelsesmuligheder"
    },
    'de-DE': {
        loading: "Lade Liedtexte",
        notFound: "Konnte die Liedtexte nicht finden.",
        writtenBy: "Geschrieben von: ",
        source: "Liedtexte bereitgestellt von: ",
        notFoundError: "Es scheint, dass wir die Liedtexte nicht anzeigen können.",
        showTranslation: "Übersetzung anzeigen",
        hideTranslation: "Übersetzung ausblenden",
        showPronunciation: "Aussprache anzeigen",
        hidePronunciation: "Aussprache ausblenden",
        showOriginal: "Original anzeigen",
        hideOriginal: "Original ausblenden",
        refreshLyrics: "Liedtexte aktualisieren",
        showTranslationOptions: "Übersetzungsoptionen anzeigen"
    },
    'et-EE': {
        loading: "Laulude sõnade laadimine",
        notFound: "Laulusõnu ei leitud.",
        writtenBy: "Kirjutanud: ",
        source: "Laulusõnad pakub: ",
        notFoundError: "Tundub, et me ei saa laulusõnu kuvada.",
        showTranslation: "Kuva tõlge",
        hideTranslation: "Peida tõlge",
        showPronunciation: "Kuva hääldus",
        hidePronunciation: "Peida hääldus",
        showOriginal: "Kuva Originaal",
        hideOriginal: "Peida Originaal",
        refreshLyrics: "Värskenda laulusõnad",
        showTranslationOptions: "Kuva tõlkevalikud"
    },
    'en-IN': {
        loading: "Loading lyrics",
        notFound: "Unable to find the lyrics.",
        writtenBy: "Written by: ",
        source: "Lyrics Provided By: ",
        notFoundError: "It seems we are unable to display the lyrics.",
        showTranslation: "Show Translation",
        hideTranslation: "Hide Translation",
        showPronunciation: "Show Pronunciation",
        hidePronunciation: "Hide Pronunciation",
        showOriginal: "Show Original",
        hideOriginal: "Hide Original",
        refreshLyrics: "Refresh Lyrics",
        showTranslationOptions: "Show Translation Options"
    },
    'en-GB': {
        loading: "Loading lyrics",
        notFound: "Unable to find the lyrics.",
        writtenBy: "Written by: ",
        source: "Lyrics Provided By: ",
        notFoundError: "It seems we are unable to display the lyrics.",
        showTranslation: "Show Translation",
        hideTranslation: "Hide Translation",
        showPronunciation: "Show Pronunciation",
        hidePronunciation: "Hide Pronunciation",
        showOriginal: "Show Original",
        hideOriginal: "Hide Original",
        refreshLyrics: "Refresh Lyrics",
        showTranslationOptions: "Show Translation Options"
    },
    'en-US': {
        loading: "Loading lyrics",
        notFound: "Unable to find the lyrics.",
        writtenBy: "Written by: ",
        source: "Lyrics Provided By: ",
        notFoundError: "It seems we are unable to display the lyrics.",
        showTranslation: "Show Translation",
        hideTranslation: "Hide Translation",
        showPronunciation: "Show Pronunciation",
        hidePronunciation: "Hide Pronunciation",
        showOriginal: "Show Original",
        hideOriginal: "Hide Original",
        refreshLyrics: "Refresh Lyrics",
        showTranslationOptions: "Show Translation Options"
    },
    'es-ES': {
        loading: "Cargando letras",
        notFound: "No se pudo encontrar la letra.",
        writtenBy: "Escrito por: ",
        source: "Letras proporcionadas por: ",
        notFoundError: "Parece que no podemos mostrar la letra.",
        showTranslation: "Mostrar Traducción",
        hideTranslation: "Ocultar Traducción",
        showPronunciation: "Mostrar Pronunciación",
        hidePronunciation: "Ocultar Pronunciación",
        showOriginal: "Mostrar Original",
        hideOriginal: "Ocultar Original",
        refreshLyrics: "Actualizar letras",
        showTranslationOptions: "Mostrar opciones de traducción"
    },
    'es-419': {
        loading: "Cargando letras",
        notFound: "No se pudo encontrar la letra.",
        writtenBy: "Escrito por: ",
        source: "Letras proporcionadas por: ",
        notFoundError: "Parece que no podemos mostrar la letra.",
        showTranslation: "Mostrar Traducción",
        hideTranslation: "Ocultar Traducción",
        showPronunciation: "Mostrar Pronunciación",
        hidePronunciation: "Ocultar Pronunciación",
        showOriginal: "Mostrar Original",
        hideOriginal: "Ocultar Original",
        refreshLyrics: "Actualizar letras",
        showTranslationOptions: "Mostrar opciones de traducción"
    },
    'es-US': {
        loading: "Cargando letras",
        notFound: "No se pudo encontrar la letra.",
        writtenBy: "Escrito por: ",
        source: "Letras proporcionadas por: ",
        notFoundError: "Parece que no podemos mostrar la letra.",
        showTranslation: "Mostrar Traducción",
        hideTranslation: "Ocultar Traducción",
        showPronunciation: "Mostrar Pronunciación",
        hidePronunciation: "Ocultar Pronunciación",
        showOriginal: "Mostrar Original",
        hideOriginal: "Ocultar Original",
        refreshLyrics: "Actualizar letras",
        showTranslationOptions: "Mostrar opciones de traducción"
    },
    'eu-ES': {
        loading: "Letrak kargatzen",
        notFound: "Ezin izan da letra aurkitu.",
        writtenBy: "Egilea: ",
        source: "Letrak hornituta: ",
        notFoundError: "Badirudi ezin ditugula letrak erakutsi.",
        showTranslation: "Erakutsi itzulpena",
        hideTranslation: "Ezkutatu itzulpena",
        showPronunciation: "Erakutsi ahoskera",
        hidePronunciation: "Ezkutatu ahoskera",
        showOriginal: "Erakutsi Originala",
        hideOriginal: "Ezkutatu Originala",
        refreshLyrics: "Letrak freskatu",
        showTranslationOptions: "Itzulpen aukerak erakutsi"
    },
    'fil-PH': {
        loading: "Nilo-load ang lyrics",
        notFound: "Hindi mahanap ang lyrics.",
        writtenBy: "Isinulat ni: ",
        source: "Lyrics Ibinigay Ni: ",
        notFoundError: "Mukhang hindi namin maipakita ang lyrics.",
        showTranslation: "Ipakita ang Pagsasalin",
        hideTranslation: "Itago ang Pagsasalin",
        showPronunciation: "Ipakita ang Pagbigkas",
        hidePronunciation: "Itago ang Pagbigkas",
        showOriginal: "Ipakita ang Orihinal",
        hideOriginal: "Itago ang Orihinal",
        refreshLyrics: "I-refresh ang lyrics",
        showTranslationOptions: "Ipakita ang mga opsyon sa pagsasalin"
    },
    'fr-FR': {
        loading: "Chargement des paroles",
        notFound: "Impossible de trouver les paroles.",
        writtenBy: "Écrit par: ",
        source: "Paroles fournies par : ",
        notFoundError: "Il semble que nous ne puissions pas afficher les paroles.",
        showTranslation: "Afficher la Traduction",
        hideTranslation: "Masquer la Traduction",
        showPronunciation: "Afficher la Prononciation",
        hidePronunciation: "Masquer la Prononciation",
        showOriginal: "Afficher l'Original",
        hideOriginal: "Masquer l'Original",
        refreshLyrics: "Actualiser les paroles",
        showTranslationOptions: "Afficher les options de traduction"
    },
    'fr-CA': {
        loading: "Chargement des paroles",
        notFound: "Impossible de trouver les paroles.",
        writtenBy: "Écrit par: ",
        source: "Paroles fournies par : ",
        notFoundError: "Il semble que nous ne puissions pas afficher les paroles.",
        showTranslation: "Afficher la traduction",
        hideTranslation: "Masquer la traduction",
        showPronunciation: "Afficher la prononciation",
        hidePronunciation: "Masquer la prononciation",
        showOriginal: "Afficher l'Original",
        hideOriginal: "Masquer l'Original",
        refreshLyrics: "Actualiser les paroles",
        showTranslationOptions: "Afficher les options de traduction"
    },
    'gl-ES': {
        loading: "Cargando letras",
        notFound: "Non se puideron atopar as letras.",
        writtenBy: "Escrito por: ",
        source: "Letras proporcionadas por: ",
        notFoundError: "Parece que non podemos mostrar as letras.",
        showTranslation: "Mostrar tradución",
        hideTranslation: "Ocultar tradución",
        showPronunciation: "Mostrar pronunciación",
        hidePronunciation: "Ocultar pronunciación",
        showOriginal: "Mostrar Orixinal",
        hideOriginal: "Ocultar Orixinal",
        refreshLyrics: "Actualizar letras",
        showTranslationOptions: "Mostrar opcións de tradución"
    },
    'hr-HR': {
        loading: "Učitavanje stihova",
        notFound: "Nije moguće pronaći stihove.",
        writtenBy: "Napisao/la: ",
        source: "Stihove osigurao/la: ",
        notFoundError: "Čini se da ne možemo prikazati stihove.",
        showTranslation: "Prikaži prijevod",
        hideTranslation: "Sakrij prijevod",
        showPronunciation: "Prikaži izgovor",
        hidePronunciation: "Sakrij izgovor",
        showOriginal: "Prikaži Original",
        hideOriginal: "Sakrij Original",
        refreshLyrics: "Osvježi stihove",
        showTranslationOptions: "Prikaži opcije prijevoda"
    },
    'zu-ZA': {
        loading: "Iyalayisha amagama",
        notFound: "Ayikwazanga ukuthola amagama.",
        writtenBy: "Ibhalwe ngu: ",
        source: "Amagama anikezwe ngu: ",
        notFoundError: "Kubukeka sengathi asikwazi ukubonisa amagama.",
        showTranslation: "Bonisa Ukuhumusha",
        hideTranslation: "Fihla Ukuhumusha",
        showPronunciation: "Bonisa Ukuphimisela",
        hidePronunciation: "Fihla Ukuphimisela",
        showOriginal: "Bonisa Okwangempela",
        hideOriginal: "Fihla Okwangempela",
        refreshLyrics: "Vuselela Amagama",
        showTranslationOptions: "Bonisa Izinketho Zokuhumusha"
    },
    'is-IS': {
        loading: "Hleð textum",
        notFound: "Gat ekki fundið textana.",
        writtenBy: "Höfundur: ",
        source: "Textar veittir af: ",
        notFoundError: "Svo virðist sem við getum ekki birt textana.",
        showTranslation: "Sýna þýðingu",
        hideTranslation: "Fela þýðingu",
        showPronunciation: "Sýna framburð",
        hidePronunciation: "Fela framburð",
        showOriginal: "Sýna Frumrit",
        hideOriginal: "Fela Frumrit",
        refreshLyrics: "Endurhlaða texta",
        showTranslationOptions: "Sýna þýðingarvalkosti"
    },
    'it-IT': {
        loading: "Caricamento dei testi",
        notFound: "Impossibile trovare i testi.",
        writtenBy: "Scritto da: ",
        source: "Testi forniti da: ",
        notFoundError: "Sembra che non possiamo mostrare i testi.",
        showTranslation: "Mostra Traduzione",
        hideTranslation: "Nascondi Traduzione",
        showPronunciation: "Mostra Pronuncia",
        hidePronunciation: "Nascondi Pronuncia",
        showOriginal: "Mostra Originale",
        hideOriginal: "Nascondi Originale",
        refreshLyrics: "Aggiorna testi",
        showTranslationOptions: "Mostra opzioni di traduzione"
    },
    'sw-KE': {
        loading: "Inapakia maneno ya wimbo",
        notFound: "Imeshindwa kupata maneno ya wimbo.",
        writtenBy: "Imeandikwa na: ",
        source: "Maneno ya wimbo yametolewa na: ",
        notFoundError: "Inaonekana hatuwezi kuonyesha maneno ya wimbo.",
        showTranslation: "Onyesha Tafsiri",
        hideTranslation: "Ficha Tafsiri",
        showPronunciation: "Onyesha Matamshi",
        hidePronunciation: "Ficha Matamshi",
        showOriginal: "Onyesha Asili",
        hideOriginal: "Ficha Asili",
        refreshLyrics: "Onyesha upya maneno ya wimbo",
        showTranslationOptions: "Onyesha chaguo za tafsiri"
    },
    'lv-LV': {
        loading: "Notiek dziesmu vārdu ielāde",
        notFound: "Nevarēja atrast dziesmas vārdus.",
        writtenBy: "Autors: ",
        source: "Dziesmu vārdus nodrošina: ",
        notFoundError: "Šķiet, ka mēs nevaram parādīt dziesmas vārdus.",
        showTranslation: "Rādīt tulkojumu",
        hideTranslation: "Slēpt tulkojumu",
        showPronunciation: "Rādīt izrunu",
        hidePronunciation: "Slēpt izrunu",
        showOriginal: "Rādīt Oriģinālu",
        hideOriginal: "Slēpt Oriģinālu",
        refreshLyrics: "Atsvaidzināt dziesmu vārdus",
        showTranslationOptions: "Rādīt tulkošanas iespējas"
    },
    'lt-LT': {
        loading: "Įkeliami dainų žodžiai",
        notFound: "Nepavyko rasti dainų žodžių.",
        writtenBy: "Parašė: ",
        source: "Dainų žodžius pateikė: ",
        notFoundError: "Atrodo, kad negalime parodyti dainų žodžių.",
        showTranslation: "Rodyti vertimą",
        hideTranslation: "Slėpti vertimą",
        showPronunciation: "Rodyti tarimą",
        hidePronunciation: "Slėpti tarimą",
        showOriginal: "Rodyti Originalą",
        hideOriginal: "Slėpti Originalą",
        refreshLyrics: "Atnaujinti dainų žodžius",
        showTranslationOptions: "Rodyti vertimo parinktis"
    },
    'hu-HU': {
        loading: "Dalszövegek betöltése",
        notFound: "Nem található a dalszöveg.",
        writtenBy: "Írta: ",
        source: "Dalszöveget biztosította: ",
        notFoundError: "Úgy tűnik, nem tudjuk megjeleníteni a dalszöveget.",
        showTranslation: "Fordítás megjelenítése",
        hideTranslation: "Fordítás elrejtése",
        showPronunciation: "Kiejtés megjelenítése",
        hidePronunciation: "Kiejtés elrejtése",
        showOriginal: "Eredeti Megjelenítése",
        hideOriginal: "Eredeti Elrejtése",
        refreshLyrics: "Dalszövegek frissítése",
        showTranslationOptions: "Fordítási lehetőségek megjelenítése"
    },
    'nl-NL': {
        loading: "Songtekst laden",
        notFound: "Songtekst niet gevonden.",
        writtenBy: "Geschreven door: ",
        source: "Songtekst geleverd door: ",
        notFoundError: "Het lijkt erop dat we de songtekst niet kunnen weergeven.",
        showTranslation: "Vertaling weergeven",
        hideTranslation: "Vertaling verbergen",
        showPronunciation: "Uitspraak weergeven",
        hidePronunciation: "Uitspraak verbergen",
        showOriginal: "Origineel Weergeven",
        hideOriginal: "Origineel Verbergen",
        refreshLyrics: "Songtekst vernieuwen",
        showTranslationOptions: "Vertalingsopties weergeven"
    },
    'no-NO': {
        loading: "Laster inn sangtekster",
        notFound: "Fant ikke sangtekstene.",
        writtenBy: "Skrevet av: ",
        source: "Sangtekster levert av: ",
        notFoundError: "Det ser ut til at vi ikke kan vise sangtekstene.",
        showTranslation: "Vis oversettelse",
        hideTranslation: "Skjul oversettelse",
        showPronunciation: "Vis uttale",
        hidePronunciation: "Skjul uttale",
        showOriginal: "Vis Original",
        hideOriginal: "Skjul Original",
        refreshLyrics: "Last inn sangtekster på nytt",
        showTranslationOptions: "Vis oversettelsesalternativer"
    },
    'uz-UZ': {
        loading: "Qo'shiq matnlari yuklanmoqda",
        notFound: "Qo'shiq matnlari topilmadi.",
        writtenBy: "Muallif: ",
        source: "Qo'shiq matnlari taqdim etilgan: ",
        notFoundError: "Ko'rinishidan, biz qo'shiq matnlarini ko'rsata olmaymiz.",
        showTranslation: "Tarjimani ko'rsatish",
        hideTranslation: "Tarjimani yashirish",
        showPronunciation: "Talaffuzni ko'rsatish",
        hidePronunciation: "Talaffuzni yashirish",
        showOriginal: "Aslini Ko'rsatish",
        hideOriginal: "Aslini Yashirish",
        refreshLyrics: "Qo'shiq matnlarini yangilash",
        showTranslationOptions: "Tarjima variantlarini ko'rsatish"
    },
    'pl-PL': {
        loading: "Ładowanie tekstu piosenki",
        notFound: "Nie można znaleźć tekstu piosenki.",
        writtenBy: "Napisane przez: ",
        source: "Tekst piosenki dostarczony przez: ",
        notFoundError: "Wygląda na to, że nie możemy wyświetlić tekstu piosenki.",
        showTranslation: "Pokaż tłumaczenie",
        hideTranslation: "Ukryj tłumaczenie",
        showPronunciation: "Pokaż wymowę",
        hidePronunciation: "Ukryj wymowę",
        showOriginal: "Pokaż Oryginał",
        hideOriginal: "Ukryj Oryginał",
        refreshLyrics: "Odśwież tekst piosenki",
        showTranslationOptions: "Pokaż opcje tłumaczenia"
    },
    'pt-PT': {
        loading: "A carregar letras",
        notFound: "Não foi possível encontrar as letras.",
        writtenBy: "Escrito por: ",
        source: "Letras fornecidas por: ",
        notFoundError: "Parece que não conseguimos apresentar as letras.",
        showTranslation: "Mostrar Tradução",
        hideTranslation: "Ocultar Tradução",
        showPronunciation: "Mostrar Pronúncia",
        hidePronunciation: "Ocultar Pronúncia",
        showOriginal: "Mostrar Original",
        hideOriginal: "Ocultar Original",
        refreshLyrics: "Atualizar Letras",
        showTranslationOptions: "Mostrar Opções de Tradução"
    },
    'pt-BR': {
        loading: "Carregando letras",
        notFound: "Não foi possível encontrar a letra.",
        writtenBy: "Escrito por: ",
        source: "Letras fornecidas por: ",
        notFoundError: "Parece que não conseguimos exibir a letra.",
        showTranslation: "Mostrar Tradução",
        hideTranslation: "Ocultar Tradução",
        showPronunciation: "Mostrar Pronúncia",
        hidePronunciation: "Ocultar Pronúncia",
        showOriginal: "Mostrar Original",
        hideOriginal: "Ocultar Original",
        refreshLyrics: "Atualizar Letras",
        showTranslationOptions: "Mostrar Opções de Tradução"
    },
    'ro-RO': {
        loading: "Se încarcă versurile",
        notFound: "Nu s-au găsit versurile.",
        writtenBy: "Scris de: ",
        source: "Versuri furnizate de: ",
        notFoundError: "Se pare că nu putem afișa versurile.",
        showTranslation: "Afișează traducerea",
        hideTranslation: "Ascunde traducerea",
        showPronunciation: "Afișează pronunția",
        hidePronunciation: "Ascunde pronunția",
        showOriginal: "Afișează Originalul",
        hideOriginal: "Ascunde Originalul",
        refreshLyrics: "Reîmprospătează versurile",
        showTranslationOptions: "Afișează opțiunile de traducere"
    },
    'sq-AL': {
        loading: "Po ngarkohen tekstet",
        notFound: "Nuk u gjetën tekstet.",
        writtenBy: "Shkruar nga: ",
        source: "Tekstet ofrohen nga: ",
        notFoundError: "Duket se nuk mund t'i shfaqim tekstet.",
        showTranslation: "Shfaq Përkthimin",
        hideTranslation: "Fshih Përkthimin",
        showPronunciation: "Shfaq Bigkasimin",
        hidePronunciation: "Fshih Bigkasimin",
        showOriginal: "Shfaq Origjinalin",
        hideOriginal: "Fshih Origjinalin",
        refreshLyrics: "Rifresko tekstet",
        showTranslationOptions: "Shfaq opsionet e përkthimit"
    },
    'sk-SK': {
        loading: "Načítavajú sa texty",
        notFound: "Nepodarilo sa nájsť texty.",
        writtenBy: "Autor: ",
        source: "Texty poskytol: ",
        notFoundError: "Zdá sa, že nemôžeme zobraziť texty.",
        showTranslation: "Zobraziť preklad",
        hideTranslation: "Skryť preklad",
        showPronunciation: "Zobraziť výslovnosť",
        hidePronunciation: "Skryť výslovnosť",
        showOriginal: "Zobraziť Originál",
        hideOriginal: "Skryť Originál",
        refreshLyrics: "Obnoviť texty",
        showTranslationOptions: "Zobraziť možnosti prekladu"
    },
    'sl-SI': {
        loading: "Nalaganje besedil",
        notFound: "Ni mogoče najti besedil.",
        writtenBy: "Avtor: ",
        source: "Besedila zagotovil: ",
        notFoundError: "Kaže, da besedil ne moremo prikazati.",
        showTranslation: "Prikaži prevod",
        hideTranslation: "Skrij prevod",
        showPronunciation: "Prikaži izgovorjavo",
        hidePronunciation: "Skrij izgovorjavo",
        showOriginal: "Prikaži Izvirnik",
        hideOriginal: "Skrij Izvirnik",
        refreshLyrics: "Osveži besedila",
        showTranslationOptions: "Prikaži možnosti prevajanja"
    },
    'sr-Latn': {
        loading: "Učitavanje teksta",
        notFound: "Nije moguće pronaći tekst.",
        writtenBy: "Napisao/la: ",
        source: "Tekst obezbedio/la: ",
        notFoundError: "Čini se da ne možemo da prikažemo tekst.",
        showTranslation: "Prikaži prevod",
        hideTranslation: "Sakrij prevod",
        showPronunciation: "Prikaži izgovor",
        hidePronunciation: "Sakrij izgovor",
        showOriginal: "Prikaži Original",
        hideOriginal: "Sakrij Original",
        refreshLyrics: "Osveži tekst",
        showTranslationOptions: "Prikaži opcije prevoda"
    },
    'fi-FI': {
        loading: "Ladataan sanoituksia",
        notFound: "Sanoituksia ei löytynyt.",
        writtenBy: "Kirjoittanut: ",
        source: "Sanoitukset toimittanut: ",
        notFoundError: "Näyttää siltä, että emme voi näyttää sanoituksia.",
        showTranslation: "Näytä käännös",
        hideTranslation: "Piilota käännös",
        showPronunciation: "Näytä ääntäminen",
        hidePronunciation: "Piilota ääntäminen",
        showOriginal: "Näytä Alkuperäinen",
        hideOriginal: "Piilota Alkuperäinen",
        refreshLyrics: "Päivitä sanoitukset",
        showTranslationOptions: "Näytä käännösvaihtoehdot"
    },
    'sv-SE': {
        loading: "Laddar låttexter",
        notFound: "Kunde inte hitta låttexten.",
        writtenBy: "Skriven av: ",
        source: "Låttexter tillhandahållna av: ",
        notFoundError: "Det verkar som att vi inte kan visa låttexten.",
        showTranslation: "Visa översättning",
        hideTranslation: "Dölj översättning",
        showPronunciation: "Visa uttal",
        hidePronunciation: "Dölj uttal",
        showOriginal: "Visa Original",
        hideOriginal: "Dölj Original",
        refreshLyrics: "Uppdatera låttexter",
        showTranslationOptions: "Visa översättningsalternativ"
    },
    'vi-VN': {
        loading: "Đang tải lời bài hát",
        notFound: "Không tìm thấy lời bài hát.",
        writtenBy: "Sáng tác: ",
        source: "Lời bài hát được cung cấp bởi: ",
        notFoundError: "Có vẻ như chúng tôi không thể hiển thị lời bài hát.",
        showTranslation: "Hiển thị bản dịch",
        hideTranslation: "Ẩn bản dịch",
        showPronunciation: "Hiển thị cách phát âm",
        hidePronunciation: "Ẩn cách phát âm",
        showOriginal: "Hiển thị Bản gốc",
        hideOriginal: "Ẩn Bản gốc",
        refreshLyrics: "Làm mới lời bài hát",
        showTranslationOptions: "Hiển thị tùy chọn dịch"
    },
    'tr-TR': {
        loading: "Şarkı sözleri yükleniyor",
        notFound: "Şarkı sözleri bulunamadı.",
        writtenBy: "Yazan: ",
        source: "Şarkı Sözleri Sağlayıcısı: ",
        notFoundError: "Görünüşe göre şarkı sözlerini görüntüleyemiyoruz.",
        showTranslation: "Çeviriyi Göster",
        hideTranslation: "Çeviriyi Gizle",
        showPronunciation: "Telaffuzu Göster",
        hidePronunciation: "Telaffuzu Gizle",
        showOriginal: "Orijinali Göster",
        hideOriginal: "Orijinali Gizle",
        refreshLyrics: "Şarkı Sözlerini Yenile",
        showTranslationOptions: "Çeviri Seçeneklerini Göster"
    },
    'be-BY': {
        loading: "Загрузка тэкстаў",
        notFound: "Немагчыма знайсці тэксты.",
        writtenBy: "Аўтар: ",
        source: "Тэксты прадастаўлены: ",
        notFoundError: "Здаецца, мы не можам адлюstraваць тэксты.",
        showTranslation: "Паказаць пераклад",
        hideTranslation: "Схаваць пераклад",
        showPronunciation: "Паказаць вымаўленне",
        hidePronunciation: "Схаваць вымаўленне",
        showOriginal: "Паказаць Арыгінал",
        hideOriginal: "Схаваць Арыгінал",
        refreshLyrics: "Абнавіць тэксты",
        showTranslationOptions: "Паказаць параметры перакладу"
    },
    'bg-BG': {
        loading: "Зареждане на текстове",
        notFound: "Не могат да бъдат намерени текстовете.",
        writtenBy: "Написано от: ",
        source: "Текстове, предоставени от: ",
        notFoundError: "Изглежда, че не можем да покажем текстовете.",
        showTranslation: "Показване на превода",
        hideTranslation: "Скриване на превода",
        showPronunciation: "Показване на произношението",
        hidePronunciation: "Скриване на произношението",
        showOriginal: "Показване на Оригинала",
        hideOriginal: "Скриване на Оригинала",
        refreshLyrics: "Опресняване на текстове",
        showTranslationOptions: "Показване на опции за превод"
    },
    'ky-KG': {
        loading: "Ырдын текстин жүктөө",
        notFound: "Ырдын тексти табылган жок.",
        writtenBy: "Автору: ",
        source: "Ырдын тексти берилди: ",
        notFoundError: "Кыязы, биз ырдын текстин көрсөтө албайбыз.",
        showTranslation: "Котормосун көрсөтүү",
        hideTranslation: "Котормосун жашыруу",
        showPronunciation: "Айтылышын көрсөтүү",
        hidePronunciation: "Айтылышын жашыруу",
        showOriginal: "Түп нусканы Көрсөтүү",
        hideOriginal: "Түп нусканы Жашыруу",
        refreshLyrics: "Ырдын текстин жаңыртуу",
        showTranslationOptions: "Котормо параметрлерин көрсөтүү"
    },
    'kk-KZ': {
        loading: "Мәтіндерді жүктеу",
        notFound: "Мәтіндер табылмады.",
        writtenBy: "Авторы: ",
        source: "Мәтіндерді ұсынған: ",
        notFoundError: "Біз мәтіндерді көрсете алмайтын сияқтымыз.",
        showTranslation: "Аудармасын көрсету",
        hideTranslation: "Аудармасын жасыру",
        showPronunciation: "Айтылуын көрсету",
        hidePronunciation: "Айтылуын жасыру",
        showOriginal: "Түпнұсқаны Көрсету",
        hideOriginal: "Түпнұсқаны Жасыру",
        refreshLyrics: "Мәтіндерді жаңарту",
        showTranslationOptions: "Аударма опцияларын көрсету"
    },
    'mk-MK': {
        loading: "Вчитување на текстови",
        notFound: "Не може да се најдат текстовите.",
        writtenBy: "Напишано од: ",
        source: "Текстови обезбедени од: ",
        notFoundError: "Изгледа дека не можеме да ги прикажеме текстовите.",
        showTranslation: "Прикажи превод",
        hideTranslation: "Сокриј превод",
        showPronunciation: "Прикажи изговор",
        hidePronunciation: "Сокриј изговор",
        showOriginal: "Прикажи Оригинал",
        hideOriginal: "Сокриј Оригинал",
        refreshLyrics: "Освежи текстови",
        showTranslationOptions: "Прикажи опции за превод"
    },
    'mn-MN': {
        loading: "Дууны үг ачааллаж байна",
        notFound: "Дууны үг олдсонгүй.",
        writtenBy: "Бичсэн: ",
        source: "Дууны үгийг хангасан: ",
        notFoundError: "Дууны үгийг харуулах боломжгүй 것 같습니다.",
        showTranslation: "Орчуулга харуулах",
        hideTranslation: "Орчуулга нуух",
        showPronunciation: "Дуудлага харуулах",
        hidePronunciation: "Дуудлага нуух",
        showOriginal: "Эх хувийг Харуулах",
        hideOriginal: "Эх хувийг Нуух",
        refreshLyrics: "Дууны үгийг шинэчлэх",
        showTranslationOptions: "Орчуулгын сонголтуудыг харуулах"
    },
    'ru-RU': {
        loading: "Загрузка текста песни",
        notFound: "Не удалось найти текст песни.",
        writtenBy: "Написано: ",
        source: "Текст песни предоставлен: ",
        notFoundError: "Похоже, мы не можем отобразить текст песни.",
        showTranslation: "Показать перевод",
        hideTranslation: "Скрыть перевод",
        showPronunciation: "Показать произношение",
        hidePronunciation: "Скрыть произношение",
        showOriginal: "Показать Оригинал",
        hideOriginal: "Скрыть Оригинал",
        refreshLyrics: "Обновить текст песни",
        showTranslationOptions: "Показать параметры перевода"
    },
    'uk-UA': {
        loading: "Завантаження текстів",
        notFound: "Не вдалося знайти тексти.",
        writtenBy: "Написано: ",
        source: "Тексти надано: ",
        notFoundError: "Здається, ми не можемо відобразити тексти.",
        showTranslation: "Показати переклад",
        hideTranslation: "Сховати переклад",
        showPronunciation: "Показати вимову",
        hidePronunciation: "Сховати вимову",
        showOriginal: "Показати Оригінал",
        hideOriginal: "Сховати Оригінал",
        refreshLyrics: "Оновити тексти",
        showTranslationOptions: "Показати параметри перекладу"
    },
    'el-GR': {
        loading: "Φόρτωση στίχων",
        notFound: "Δεν ήταν δυνατή η εύρεση των στίχων.",
        writtenBy: "Συνθέτης: ",
        source: "Στίχοι Παρέχονται Από: ",
        notFoundError: "Φαίνεται ότι δεν μπορούμε να εμφανίσουμε τους στίχους.",
        showTranslation: "Εμφάνιση μετάφρασης",
        hideTranslation: "Απόκρυψη μετάφρασης",
        showPronunciation: "Εμφάνιση προφοράς",
        hidePronunciation: "Απόκρυψη προφοράς",
        showOriginal: "Εμφάνιση Πρωτότυπου",
        hideOriginal: "Απόκρυψη Πρωτότυπου",
        refreshLyrics: "Ανανέωση στίχων",
        showTranslationOptions: "Εμφάνιση επιλογών μετάφρασης"
    },
    'hy-AM': {
        loading: "Բեռնվում են բառերը",
        notFound: "Չհաջողվեց գտնել բառերը:",
        writtenBy: "Հեղինակ՝ ",
        source: "Բառերը տրամադրել է՝ ",
        notFoundError: "Կարծես թե չենք կարողանում ցուցադրել բառերը:",
        showTranslation: "Ցուցադրել թարգմանությունը",
        hideTranslation: "Թաքցնել թարգմանությունը",
        showPronunciation: "Ցուցադրել արտասանությունը",
        hidePronunciation: "Թաքցնել արտասանությունը",
        showOriginal: "Ցուցադրել Բնօրինակը",
        hideOriginal: "Թաքցնել Բնօրինակը",
        refreshLyrics: "Թարմացնել բառերը",
        showTranslationOptions: "Ցուցադրել թարգմանության ընտրանքները"
    },
    'he-IL': {
        loading: "טוען מילים",
        notFound: "לא ניתן למצוא את המילים.",
        writtenBy: "נכתב על ידי: ",
        source: "מילים סופקו על ידי: ",
        notFoundError: "נראה שאנחנו לא יכולים להציג את המילים.",
        showTranslation: "הצג תרגום",
        hideTranslation: "הסתר תרגום",
        showPronunciation: "הצג הגייה",
        hidePronunciation: "הסתר הגייה",
        showOriginal: "הצג מקור",
        hideOriginal: "הסתר מקור",
        refreshLyrics: "רענן מילים",
        showTranslationOptions: "הצג אפשרויות תרגום"
    },
    'ur-PK': {
        loading: "دھن لوڈ ہو رہی ہے",
        notFound: "دھن نہیں مل سکی۔",
        writtenBy: "لکھا ہوا: ",
        source: "دھن فراہم کردہ: ",
        notFoundError: "ایسا لگتا ہے کہ ہم دھن نہیں دکھا سکتے۔",
        showTranslation: "ترجمہ دکھائیں",
        hideTranslation: "ترجمہ چھپائیں",
        showPronunciation: "تلفظ دکھائیں",
        hidePronunciation: "تلفظ چھپائیں",
        showOriginal: "اصل دکھائیں",
        hideOriginal: "اصل چھپائیں",
        refreshLyrics: "دھن تازہ کریں",
        showTranslationOptions: "ترجمہ کے اختیارات دکھائیں"
    },
    'ar-SA': {
        loading: "جارٍ تحميل كلمات الأغنية",
        notFound: "تعذر العثور على كلمات الأغنية.",
        writtenBy: "كتبه: ",
        source: "كلمات الأغنية مقدمة من: ",
        notFoundError: "يبدو أننا غير قادرين على عرض كلمات الأغنية.",
        showTranslation: "عرض الترجمة",
        hideTranslation: "إخفاء الترجمة",
        showPronunciation: "عرض النطق",
        hidePronunciation: "إخفاء النطق",
        showOriginal: "عرض الأصل",
        hideOriginal: "إخفاء الأصل",
        refreshLyrics: "تحديث كلمات الأغنية",
        showTranslationOptions: "إظهار خيارات الترجمة"
    },
    'fa-IR': {
        loading: "در حال بارگیری متن ترانه",
        notFound: "متن ترانه پیدا نشد.",
        writtenBy: "نوشته شده توسط: ",
        source: "متن ترانه ارائه شده توسط: ",
        notFoundError: "به نظر می رسد ما قادر به نمایش متن ترانه نیستیم.",
        showTranslation: "نمایش ترجمه",
        hideTranslation: "پنهان کردن ترجمه",
        showPronunciation: "نمایش تلفظ",
        hidePronunciation: "پنهان کردن تلفظ",
        showOriginal: "نمایش اصلی",
        hideOriginal: "پنهان کردن اصلی",
        refreshLyrics: "بازخوانی متن ترانه",
        showTranslationOptions: "نمایش گزینه های ترجمه"
    },
    'ne-NP': {
        loading: "गीतको बोल लोड हुँदैछ",
        notFound: "गीतको बोल फेला पार्न सकिएन।",
        writtenBy: "द्वारा लिखित: ",
        source: "गीतको बोल द्वारा प्रदान गरिएको: ",
        notFoundError: "यस्तो देखिन्छ कि हामी गीतको बोल प्रदर्शन गर्न असमर्थ छौं।",
        showTranslation: "अनुवाद देखाउनुहोस्",
        hideTranslation: "अनुवाद लुकाउनुहोस्",
        showPronunciation: "उच्चारण देखाउनुहोस्",
        hidePronunciation: "उच्चारण लुकाउनुहोस्",
        showOriginal: "मूल देखाउनुहोस्",
        hideOriginal: "मूल लुकाउनुहोस्",
        refreshLyrics: "गीतको बोल रिफ्रेस गर्नुहोस्",
        showTranslationOptions: "अनुवाद विकल्पहरू देखाउनुहोस्"
    },
    'mr-IN': {
        loading: "गीत लोड होत आहे",
        notFound: "गीत सापडले नाही.",
        writtenBy: "लिहिले आहे: ",
        source: "गीत यांनी प्रदान केले: ",
        notFoundError: "असे दिसते की आम्ही गीत प्रदर्शित करू शकत नाही.",
        showTranslation: "अनुवाद दर्शवा",
        hideTranslation: "अनुवाद लपवा",
        showPronunciation: "उच्चार दर्शवा",
        hidePronunciation: "उच्चार लपवा",
        showOriginal: "मूळ दर्शवा",
        hideOriginal: "मूळ लपवा",
        refreshLyrics: "गीत रीफ्रेश करा",
        showTranslationOptions: "अनुवाद पर्याय दर्शवा"
    },
    'hi-IN': {
        loading: "गीत लोड हो रहा है",
        notFound: "गीत के बोल नहीं मिले।",
        writtenBy: "लेखक: ",
        source: "गीत के बोल प्रदान किए गए: ",
        notFoundError: "ऐसा लगता है कि हम गीत के बोल प्रदर्शित नहीं कर सकते।",
        showTranslation: "अनुवाद दिखाएँ",
        hideTranslation: "अनुवाद छिपाएँ",
        showPronunciation: "उच्चारण दिखाएँ",
        hidePronunciation: "उच्चारण छिपाएँ",
        showOriginal: "मूल दिखाएँ",
        hideOriginal: "मूल छिपाएँ",
        refreshLyrics: "गीत रीफ्रेश करें",
        showTranslationOptions: "अनुवाद विकल्प दिखाएँ"
    },
    'as-IN': {
        loading: "गीতৰ কথা লোড হৈ আছে",
        notFound: "गीতৰ কথা বিচাৰি পোৱা ন'গ'ল।",
        writtenBy: "द्वारा লিখিত: ",
        source: "গানের কথা দিছে: ",
        notFoundError: " এনে লাগিছে যে আমি गीतৰ কথা প্ৰদৰ্শন কৰিবলৈ অক্ষম।",
        showTranslation: "অনুবাদ দেখুৱাওক",
        hideTranslation: "অনুবাদ লুকুৱাওক",
        showPronunciation: "উচ্চাৰণ দেখুৱাওক",
        hidePronunciation: "উচ্চাৰণ লুকুৱাওк",
        showOriginal: "মূল দেখুৱাওক",
        hideOriginal: "মূল লুকুৱাওক",
        refreshLyrics: "গানের কথা সতেজ কৰক",
        showTranslationOptions: "অনুবাদ বিকল্প দেখুৱাওক"
    },
    'bn-IN': {
        loading: "গানের কথা লোড হচ্ছে",
        notFound: "গানের কথা খুঁজে পাওয়া যায়নি।",
        writtenBy: "লিখেছেন: ",
        source: "গানের কথা সরবরাহ করেছে: ",
        notFoundError: "মনে হচ্ছে আমরা গানের কথা প্রদর্শন করতে পারছি না।",
        showTranslation: "অনুবাদ দেখান",
        hideTranslation: "অনুবাদ লুকান",
        showPronunciation: "উচ্চারণ দেখান",
        hidePronunciation: "উচ্চারণ লুকান",
        showOriginal: "মূল দেখান",
        hideOriginal: "মূল লুকান",
        refreshLyrics: "গানের কথা রিফ্রেশ করুন",
        showTranslationOptions: "অনুবাদ বিকল্প দেখান"
    },
    'pa-IN': {
        loading: "ਬੋਲ ਲੋਡ ਹੋ ਰਹੇ ਹਨ",
        notFound: "ਬੋਲ ਨਹੀਂ ਮਿਲ ਸਕੇ।",
        writtenBy: "ਦੁਆਰਾ ਲਿਖਿਆ ਗਿਆ: ",
        source: "ਬੋਲ ਦੁਆਰਾ ਪ੍ਰਦਾਨ ਕੀਤੇ ਗਏ: ",
        notFoundError: "ਅਜਿਹਾ ਲਗਦਾ ਹੈ ਕਿ ਅਸੀਂ ਬੋਲ ਪ੍ਰਦਰਸ਼ਿਤ ਕਰਨ ਵਿੱਚ ਅਸਮਰੱਥ ਹਾਂ।",
        showTranslation: "ਅਨੁਵਾਦ ਦਿਖਾਓ",
        hideTranslation: "ਅਨੁਵਾਦ ਛੁਪਾਓ",
        showPronunciation: "ਉਚਾਰਨ ਦਿਖਾਓ",
        hidePronunciation: "ਉਚਾਰਨ ਛੁਪਾਓ",
        showOriginal: "ਮੂਲ ਦਿਖਾਓ",
        hideOriginal: "ਮੂਲ ਛੁਪਾਓ",
        refreshLyrics: "ਬੋਲ ਤਾਜ਼ਾ ਕਰੋ",
        showTranslationOptions: "ਅਨੁਵਾਦ ਵਿਕਲਪ ਦਿਖਾਓ"
    },
    'gu-IN': {
        loading: "ગીતના બોલ લોડ થઈ રહ્યા છે",
        notFound: "ગીતના બોલ શોધી શકાયા નથી.",
        writtenBy: "દ્વારા લખાયેલ: ",
        source: "ગીતના બોલ દ્વારા પ્રદાન કરેલ: ",
        notFoundError: "એવું લાગે છે કે અમે ગીતના બોલ પ્રદર્શિત કરવામાં અસમર્થ છીએ.",
        showTranslation: "અનુવાદ બતાવો",
        hideTranslation: "અનુવાદ છુપાવો",
        showPronunciation: "ઉચ્ચાર બતાવો",
        hidePronunciation: "ઉચ્ચાર છુપાવો",
        showOriginal: "મૂળ બતાવો",
        hideOriginal: "મૂળ છુપાવો",
        refreshLyrics: "ગીતના બોલ તાજા કરો",
        showTranslationOptions: "અનુવાદ વિકલ્પો બતાવો"
    },
    'or-IN': {
        loading: "ଗୀତର ବୋଲ ଲୋଡ୍ କରୁଛି",
        notFound: "ଗୀତର ବୋଲ ମିଳିଲା ନାହିଁ |",
        writtenBy: "ଏହା ଦ୍ୱାରା ଲିଖିତ: ",
        source: "ଗୀତର ବୋଲ ଏହା ଦ୍ୱାରା ପ୍ରଦାନ କରାଯାଇଛି: ",
        notFoundError: "ଏହା ଜଣାପଡୁଛି ଯେ ଆମେ ଗୀତର ବୋଲ ପ୍ରଦର୍ଶନ କରିବାରେ ଅସମର୍ଥ |",
        showTranslation: "ଅନୁବାଦ ଦେଖାନ୍ତୁ",
        hideTranslation: "ଅନୁବାଦ ଲୁଚାନ୍ତୁ",
        showPronunciation: "ଉଚ୍ଚାରଣ ଦେଖାନ୍ତୁ",
        hidePronunciation: "ଉଚ୍ଚାରଣ ଲୁଚାନ୍ତୁ",
        showOriginal: "ମୂଳ ଦେଖାନ୍ତୁ",
        hideOriginal: "ମୂଳ ଲୁଚାନ୍ତୁ",
        refreshLyrics: "ଗୀତର ବୋଲ ରିଫ୍ରେସ୍ କରନ୍ତୁ",
        showTranslationOptions: "ଅନୁବାଦ ବିକଳ୍ପ ଦେଖାନ୍ତୁ"
    },
    'ta-IN': {
        loading: "பாடல் வரிகள் ஏற்றಲಾಗುತ್ತಿದೆ",
        notFound: "பாடல் வரிகளைக் கண்டுபிடிக்க முடியவில்லை.",
        writtenBy: "எழுதியவர்: ",
        source: "பாடல் வரிகள் வழங்கியவர்: ",
        notFoundError: "பாடல் வரிகளைக் காட்ட முடியவில்லை என்று தெரிகிறது.",
        showTranslation: "மொழிபெயர்ப்பைக் காட்டு",
        hideTranslation: "மொழிபெயர்ப்பை மறை",
        showPronunciation: "உச்சரிப்பைக் காட்டு",
        hidePronunciation: "உச்சரிப்பை மறை",
        showOriginal: "அசல் காட்டு",
        hideOriginal: "அசல் மறை",
        refreshLyrics: "பாடல் வரிகளைப் புதுப்பி",
        showTranslationOptions: "மொழிபெயர்ப்பு விருப்பங்களைக் காட்டு"
    },
    'te-IN': {
        loading: "సాహిత్యం లోడ్ అవుతోంది",
        notFound: "సాహిత్యాన్ని కనుగొనలేకపోయింది.",
        writtenBy: "రాసినవారు: ",
        source: "సాహిత్యం అందించినవారు: ",
        notFoundError: "మేము సాహిత్యాన్ని ప్రదర్శించలేమని తెలుస్తోంది.",
        showTranslation: "అనువాదాన్ని చూపించు",
        hideTranslation: "అనువాదాన్ని దాచు",
        showPronunciation: "ఉచ్చారణను చూపించు",
        hidePronunciation: "ఉచ్చారణను దాచు",
        showOriginal: "అసలు చూపించు",
        hideOriginal: "అసలు దాచు",
        refreshLyrics: "సాహిత్యాన్ని రిఫ్రెష్ చేయండి",
        showTranslationOptions: "అనువాద ఎంపికలను చూపించు"
    },
    'kn-IN': {
        loading: "ಸಾಹಿತ್ಯವನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ",
        notFound: "ಸಾಹಿತ್ಯವನ್ನು ಹುಡುಕಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.",
        writtenBy: "ಬರೆದವರು: ",
        source: "ಸಾಹಿತ್ಯವನ್ನು ಒದಗಿಸಿದವರು: ",
        notFoundError: "ನಾವು ಸಾಹಿತ್ಯವನ್ನು ಪ್ರದರ್ಶಿಸಲು ಸಾಧ್ಯವಾಗುತ್ತಿಲ್ಲ ಎಂದು ತೋರುತ್ತದೆ.",
        showTranslation: "ಅನುವಾದವನ್ನು ತೋರಿಸಿ",
        hideTranslation: "ಅನುವಾದವನ್ನು ಮರೆಮಾಡಿ",
        showPronunciation: "ಉಚ್ಚಾರಣೆಯನ್ನು ತೋರಿಸಿ",
        hidePronunciation: "ಉಚ್ಚಾರಣೆಯನ್ನು ಮರೆಮಾಡಿ",
        showOriginal: "ಮೂಲವನ್ನು ತೋರಿಸಿ",
        hideOriginal: "ಮೂಲವನ್ನು ಮರೆಮಾಡಿ",
        refreshLyrics: "ಸಾಹಿತ್ಯವನ್ನು ರಿಫ್ರೆಶ್ ಮಾಡಿ",
        showTranslationOptions: "ಅನುವಾದ ಆಯ್ಕೆಗಳನ್ನು ತೋರಿಸಿ"
    },
    'ml-IN': {
        loading: "വരികൾ ലോഡുചെയ്യുന്നു",
        notFound: "വരികൾ കണ്ടെത്താനായില്ല.",
        writtenBy: "എഴുതിയത്: ",
        source: "വരികൾ നൽകിയത്: ",
        notFoundError: "വരികൾ പ്രദർശിപ്പിക്കാൻ ഞങ്ങൾക്ക് കഴിയില്ലെന്ന് തോന്നുന്നു.",
        showTranslation: "പരിഭാഷ കാണിക്കുക",
        hideTranslation: "പരിഭാഷ മറയ്ക്കുക",
        showPronunciation: "ഉച്ചാരണം കാണിക്കുക",
        hidePronunciation: "ഉച്ചാരണം മറയ്ക്കുക",
        showOriginal: "യഥാർത്ഥ കാണിക്കുക",
        hideOriginal: "യഥാർത്ഥ മറയ്ക്കുക",
        refreshLyrics: "വരികൾ പുതുക്കുക",
        showTranslationOptions: "വിവർത്തന ഓപ്ഷനുകൾ കാണിക്കുക"
    },
    'si-LK': {
        loading: "පද රචනය පූරණය වෙමින් පවතී",
        notFound: "පද රචනය සොයාගත නොහැකි විය.",
        writtenBy: "ලියන ලද්දේ: ",
        source: "පද රචනය සපයන ලද්දේ: ",
        notFoundError: "අපට පද රචනය ප්‍රදර්ශනය කළ නොහැකි බව පෙනේ.",
        showTranslation: "පරිවර්තනය පෙන්වන්න",
        hideTranslation: "පරිවර්තනය සඟවන්න",
        showPronunciation: "උච්චාරණය පෙන්වන්න",
        hidePronunciation: "උච්චාරණය සඟවන්න",
        showOriginal: "මුල් පිටපත පෙන්වන්න",
        hideOriginal: "මුල් පිටපත සඟවන්න",
        refreshLyrics: "පද රචනය නැවත පූരණය කරන්න",
        showTranslationOptions: "පරිවර්තන විකල්ප පෙන්වන්න"
    },
    'th-TH': {
        loading: "กำลังโหลดเนื้อเพลง",
        notFound: "ไม่พบเนื้อเพลง",
        writtenBy: "ประพันธ์โดย: ",
        source: "เนื้อเพลงโดย: ",
        notFoundError: "ดูเหมือนว่าเราจะไม่สามารถแสดงเนื้อเพลงได้",
        showTranslation: "แสดงคำแปล",
        hideTranslation: "ซ่อนคำแปล",
        showPronunciation: "แสดงการออกเสียง",
        hidePronunciation: "ซ่อนการออกเสียง",
        showOriginal: "แสดงต้นฉบับ",
        hideOriginal: "ซ่อนต้นฉบับ",
        refreshLyrics: "รีเฟรชเนื้อเพลง",
        showTranslationOptions: "แสดงตัวเลือกการแปล"
    },
    'lo-LA': {
        loading: "ກຳລັງໂຫລດເນື້ອເພງ",
        notFound: "ບໍ່ສາມາດຊອກຫາເນື້ອເພງໄດ້.",
        writtenBy: "ຂຽນໂດຍ: ",
        source: "ເນື້ອເພງສະໜອງໃຫ້ໂດຍ: ",
        notFoundError: "ເບິ່ງຄືວ່າພວກເຮົາບໍ່ສາມາດສະແດງເນື້ອເພງໄດ້.",
        showTranslation: "ສະແດງການແປ",
        hideTranslation: "ເຊື່ອງການແປ",
        showPronunciation: "ສະແດງການອອກສຽງ",
        hidePronunciation: "ເຊື່ອງການອອກສຽງ",
        showOriginal: "ສະແດງຕົ້ນສະບັບ",
        hideOriginal: "ເຊື່ອງຕົ້ນສະບັບ",
        refreshLyrics: "ໂຫຼດເນື້ອເພງຄືນໃໝ່",
        showTranslationOptions: "ສະແດງຕົວເລືອກການແປ"
    },
    'my-MM': {
        loading: "စာသားများအား တင်နေသည်",
        notFound: "စာသားများ ရှာမတွေ့ပါ။",
        writtenBy: "ရေးသားသူ: ",
        source: "စာသားများအား ပံ့ပိုးပေးသည်- ",
        notFoundError: "ကျွန်ုပ်တို့ စာသားများအား ပြသနိုင်ခြင်း မရှိပုံပေါ်ပါသည်။",
        showTranslation: "ဘာသာပြန်ချက်ကို ပြပါ",
        hideTranslation: "ဘာသာပြန်ချက်ကို ဖျောက်ပါ",
        showPronunciation: "အသံထွက်ကို ပြပါ",
        hidePronunciation: "အသံထွက်ကို ဖျောက်ပါ",
        showOriginal: "မူရင်းကို ပြပါ",
        hideOriginal: "မူရင်းကို ဖျောက်ပါ",
        refreshLyrics: "စာသားများအား ပြန်လည်စတင်ပါ",
        showTranslationOptions: "ဘာသာပြန်ရွေးချယ်စရာများကို ပြပါ"
    },
    'ka-GE': {
        loading: "იტვირთება ტექსტები",
        notFound: "ტექსტები ვერ მოიძებნა.",
        writtenBy: "ავტორი: ",
        source: "ტექსტები მოწოდებულია: ",
        notFoundError: "როგორც ჩანს, ტექსტებს ვერ ვაჩვენებთ.",
        showTranslation: "თარგმანის ჩვენება",
        hideTranslation: "თარგმანის დამალვა",
        showPronunciation: "წარმოთქმის ჩვენება",
        hidePronunciation: "წარმოთქმის დამალვა",
        showOriginal: "ორიგინალის ჩვენება",
        hideOriginal: "ორიგინალის დამალვა",
        refreshLyrics: "ტექსტების განახლება",
        showTranslationOptions: "თარგმანის პარამეტრების ჩვენება"
    },
    'am-ET': {
        loading: "ግጥሞችን በመጫን ላይ",
        notFound: "ግጥሞቹን ማግኘት አልተቻለም።",
        writtenBy: "የተፃፈው በ: ",
        source: "ግጥሞች የቀረቡት በ: ",
        notFoundError: "ግጥሞቹን ማሳየት ያልቻልን ይመስላል።",
        showTranslation: "ትርጉም አሳይ",
        hideTranslation: "ትርጉም ደብቅ",
        showPronunciation: "አነባበብ አሳይ",
        hidePronunciation: "አነባበብ ደብቅ",
        showOriginal: "ዋናውን አሳይ",
        hideOriginal: "ዋናውን ደብቅ",
        refreshLyrics: "ግጥሞችን አድስ",
        showTranslationOptions: "የትርጉም አማራጮችን አሳይ"
    },
    'km-KH': {
        loading: "កំពុង​ផ្ទុក​អត្ថបទ​ចម្រៀង",
        notFound: "​មិន​អាច​រក​ឃើញ​អត្ថបទ​ចម្រៀង​ទេ។",
        writtenBy: "និពន្ធ​โดย: ",
        source: "អត្ថបទ​ចម្រៀង​ផ្ដល់​ให้​โดย: ",
        notFoundError: "ហាក់​ដូច​ជា​យើង​មិន​អាច​បង្ហាញ​អត្ថបទ​ចម្រៀង​បាន​ទេ។",
        showTranslation: "បង្ហាញ​ការ​បកប្រែ",
        hideTranslation: "លាក់​ការ​បកប្រែ",
        showPronunciation: "បង្ហាញ​ការ​បញ្ចេញ​សំឡេង",
        hidePronunciation: "លាក់​ការ​បញ្ចេញ​សំឡេង",
        showOriginal: "បង្ហាញ​ដើម",
        hideOriginal: "លាក់​ដើម",
        refreshLyrics: "ផ្ទុក​អត្ថបទ​ចម្រៀង​ឡើងវិញ",
        showTranslationOptions: "បង្ហាញ​ជម្រើស​បកប្រែ"
    },
    'zh-CN': {
        loading: "加载歌词",
        notFound: "无法找到歌词。",
        writtenBy: "作者: ",
        source: "歌词提供方: ",
        notFoundError: "看起来我们无法显示歌词。",
        showTranslation: "显示翻译",
        hideTranslation: "隐藏翻译",
        showPronunciation: "显示发音",
        hidePronunciation: "隐藏发音",
        showOriginal: "显示原文",
        hideOriginal: "隐藏原文",
        refreshLyrics: "刷新歌词",
        showTranslationOptions: "显示翻译选项"
    },
    'zh-TW': {
        loading: "載入歌詞",
        notFound: "找不到歌詞。",
        writtenBy: "作者：",
        source: "歌詞提供：",
        notFoundError: "我們似乎無法顯示歌詞。",
        showTranslation: "顯示翻譯",
        hideTranslation: "隱藏翻譯",
        showPronunciation: "顯示發音",
        hidePronunciation: "隱藏發音",
        showOriginal: "顯示原文",
        hideOriginal: "隱藏原文",
        refreshLyrics: "重新整理歌詞",
        showTranslationOptions: "顯示翻譯選項"
    },
    'zh-HK': {
        loading: "載入歌詞",
        notFound: "找不到歌詞。",
        writtenBy: "作者：",
        source: "歌詞提供：",
        notFoundError: "我們似乎無法顯示歌詞。",
        showTranslation: "顯示翻譯",
        hideTranslation: "隱藏翻譯",
        showPronunciation: "顯示發音",
        hidePronunciation: "隱藏發音",
        showOriginal: "顯示原文",
        hideOriginal: "隱藏原文",
        refreshLyrics: "重新整理歌詞",
        showTranslationOptions: "顯示翻譯選項"
    },
    'ja-JP': {
        loading: "歌詞を読み込んでいます",
        notFound: "歌詞が見つかりませんでした。",
        writtenBy: "作詞: ",
        source: "歌詞提供: ",
        notFoundError: "歌詞を表示できないようです。",
        showTranslation: "翻訳を表示",
        hideTranslation: "翻訳を非表示",
        showPronunciation: "発音を表示",
        hidePronunciation: "発音を非表示",
        showOriginal: "オリジナルを表示",
        hideOriginal: "オリジナルを非表示",
        refreshLyrics: "歌詞を更新",
        showTranslationOptions: "翻訳オプションを表示"
    },
    'ko-KR': {
        loading: "가사 불러오는 중",
        notFound: "가사를 찾을 수 없습니다.",
        writtenBy: "작사: ",
        source: "가사 제공: ",
        notFoundError: "가사를 표시할 수 없는 것 같습니다.",
        showTranslation: "번역 보기",
        hideTranslation: "번역 숨기기",
        showPronunciation: "발음 보기",
        hidePronunciation: "발음 숨기기",
        showOriginal: "원본 보기",
        hideOriginal: "원본 숨기기",
        refreshLyrics: "가사 새로고침",
        showTranslationOptions: "번역 옵션 표시"
    }
};

function getUserLanguage() {
    // Get the browser's language, default to 'en-US' if not available.
    const userLang = document.documentElement.lang || 'en-US';

    if (userLang in translations) {
        return userLang;
    }
    const baseLang = userLang.split('-')[0];

    if (baseLang in translations) {
        return baseLang;
    }

    for (const key in translations) {
        if (key.startsWith(baseLang + '-')) {
            return key; // Return the first matching dialect we find.
        }
    }

    //If no match could be found at all, return the ultimate default.
    return 'en-US';
}

function t(key) {
    const lang = getUserLanguage();
    return translations[lang]?.[key] || translations['en-US'][key];
}